"""initial_schema

Revision ID: c5dde5f8885e
Revises:
Create Date: 2026-04-18 01:20:12.459983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5dde5f8885e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "novels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cover_image_path", sa.String(length=500), nullable=True),
        sa.Column("source_language", sa.String(length=10), nullable=False),
        sa.Column("target_language", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chapters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("novel_id", sa.Integer(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("original_content", sa.Text(), nullable=False),
        sa.Column("translated_content", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "novel_id", "chapter_number", name="uq_chapters_novel_number"
        ),
    )
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chapters_novel_id"), ["novel_id"], unique=False
        )

    op.create_table(
        "glossary_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("novel_id", sa.Integer(), nullable=False),
        sa.Column("source_term", sa.String(length=200), nullable=False),
        sa.Column("target_term", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.String(length=100),
            nullable=False,
            comment="E.g. Nhân vật, Địa danh, Môn phái, Công pháp, Vũ khí, ...",
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("novel_id", "source_term", name="uq_glossary_novel_term"),
    )
    with op.batch_alter_table("glossary_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_glossary_entries_novel_id"), ["novel_id"], unique=False
        )

    op.create_table(
        "translation_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("translated_text", sa.Text(), nullable=True),
        sa.Column("review_feedback", sa.Text(), nullable=True),
        sa.Column("review_verdict", sa.String(length=10), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("translation_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_translation_jobs_chapter_id"), ["chapter_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("translation_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_translation_jobs_chapter_id"))

    op.drop_table("translation_jobs")
    with op.batch_alter_table("glossary_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_glossary_entries_novel_id"))

    op.drop_table("glossary_entries")
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chapters_novel_id"))

    op.drop_table("chapters")
    op.drop_table("novels")
    # ### end Alembic commands ###
